feat(shell script): use native script

diff --git a/src/pre-commit b/src/pre-commit
--- a/src/pre-commit
+++ b/src/pre-commit
@@ -1,19 +1,43 @@
-#!/usr/bin/env php
-<?php
+#!/bin/sh
 
-$phpcsCommand = "./vendor/bin/phpcs --standard=PSR2 --encoding=utf-8";
-$files = shell_exec("git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php");
-$files = array_filter(explode(PHP_EOL, $files), function ($value) {
-    return strlen($value) > 3 && is_file($value) && preg_match('/(tests|database|vendor)\//', $value) === 0;
-});
-$errorCount = 0;
-foreach ($files as $file) {
-    $jsonReport = shell_exec($phpcsCommand." --report=json ".$file);
-    $totals = json_decode($jsonReport, true)['totals'];
-    $count = $totals['errors'] + $totals['warnings'];
-    $errorCount += $count;
-    if ($count > 0) {
-        print_r(shell_exec($phpcsCommand." -n ".$file));
-    }
-}
-exit($errorCount === 0 ? 0 : 1);
+PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
+STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`
+
+# Determine if a file list is passed
+if [ "$#" -eq 1 ]
+then
+    oIFS=$IFS
+    IFS='
+    '
+    SFILES="$1"
+    IFS=$oIFS
+fi
+SFILES=${SFILES:-$STAGED_FILES_CMD}
+
+echo "Checking PHP Lint..."
+for FILE in $SFILES
+do
+    php -l -d display_errors=0 $PROJECT/$FILE
+    if [ $? != 0 ]
+    then
+        echo "Fix the error before commit."
+        exit 1
+    fi
+    FILES="$FILES $PROJECT/$FILE"
+done
+
+if [ "$FILES" != "" ]
+then
+    echo "Running Code Sniffer. Code standard PSR2."
+    ./vendor/bin/phpcs --standard=PSR2 --colors --encoding=utf-8 -n -p $FILES
+    if [ $? != 0 ]
+    then
+        echo "Fix the error before commit!"
+        echo "Run"
+        echo "  ./vendor/bin/phpcbf --standard=PSR2 $FILES"
+        echo "for automatic fix or fix it manually."
+        exit 1
+    fi
+fi
+
+exit $?
